// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: cart.sql

package db

import (
	"context"
	"database/sql"
)

const addItemToCart = `-- name: AddItemToCart :exec
CALL add_to_cart($1,$2,$3)
`

type AddItemToCartParams struct {
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) AddItemToCart(ctx context.Context, arg AddItemToCartParams) error {
	_, err := q.db.ExecContext(ctx, addItemToCart, arg.ProductID, arg.Quantity, arg.UserID)
	return err
}

const getCartID = `-- name: GetCartID :one
select cart_id from carts where user_id = $1
`

func (q *Queries) GetCartID(ctx context.Context, userID sql.NullInt32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCartID, userID)
	var cart_id int32
	err := row.Scan(&cart_id)
	return cart_id, err
}

const insertCartItem = `-- name: InsertCartItem :exec
insert into cart_details (cart_id,product_id,product_price,quantity,delivery_price)
values($1,$2,(select price from products p where p.product_id = $2),$3,
(select delivery_price from products p where p.product_id = $2))
`

type InsertCartItemParams struct {
	CartID    sql.NullInt32 `json:"cart_id"`
	ProductID sql.NullInt32 `json:"product_id"`
	Quantity  sql.NullInt32 `json:"quantity"`
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	return err
}

const isProductInCart = `-- name: IsProductInCart :one
select case when exists (select product_id from v_cart vc where product_id = $1 and user_id = $2)
then 1 else 0 end is_product_in_cart
`

type IsProductInCartParams struct {
	ProductID sql.NullInt32 `json:"product_id"`
	UserID    sql.NullInt32 `json:"user_id"`
}

func (q *Queries) IsProductInCart(ctx context.Context, arg IsProductInCartParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, isProductInCart, arg.ProductID, arg.UserID)
	var is_product_in_cart interface{}
	err := row.Scan(&is_product_in_cart)
	return is_product_in_cart, err
}

const readCartItemQuantity = `-- name: ReadCartItemQuantity :one
select quantity from v_cart vc where product_id = $1 and user_id = $2
`

type ReadCartItemQuantityParams struct {
	ProductID sql.NullInt32 `json:"product_id"`
	UserID    sql.NullInt32 `json:"user_id"`
}

func (q *Queries) ReadCartItemQuantity(ctx context.Context, arg ReadCartItemQuantityParams) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, readCartItemQuantity, arg.ProductID, arg.UserID)
	var quantity sql.NullInt32
	err := row.Scan(&quantity)
	return quantity, err
}

const removeItemFromCart = `-- name: RemoveItemFromCart :exec
CALL remove_item($1,$2,$3)
`

type RemoveItemFromCartParams struct {
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) RemoveItemFromCart(ctx context.Context, arg RemoveItemFromCartParams) error {
	_, err := q.db.ExecContext(ctx, removeItemFromCart, arg.ProductID, arg.Quantity, arg.UserID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
update cart_details set quantity = $1 + quantity where product_id = $2 and cart_id = $3
`

type UpdateCartItemQuantityParams struct {
	Quantity  sql.NullInt32 `json:"quantity"`
	ProductID sql.NullInt32 `json:"product_id"`
	CartID    sql.NullInt32 `json:"cart_id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateCartItemQuantity, arg.Quantity, arg.ProductID, arg.CartID)
	return err
}
