// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	FindUserOne(ctx context.Context, email string) (FindUserOneRow, error)
	GetCartID(ctx context.Context, userID sql.NullInt32) (int32, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) error
	ReadAllCategories(ctx context.Context) ([]ReadAllCategoriesRow, error)
	ReadAllProducts(ctx context.Context, arg ReadAllProductsParams) ([]ReadAllProductsRow, error)
	ReadCategoryItems(ctx context.Context, arg ReadCategoryItemsParams) ([]ReadCategoryItemsRow, error)
	ReadCategoryProduct(ctx context.Context, categoryID int32) ([]VProduct, error)
	ReadOneCategory(ctx context.Context, categoryID int32) (ReadOneCategoryRow, error)
	ReadOneProduct(ctx context.Context, productID int32) (ReadOneProductRow, error)
	ReadProductQuantityInCard(ctx context.Context, arg ReadProductQuantityInCardParams) (int64, error)
	ReadQuantity(ctx context.Context, productID int32) (sql.NullInt32, error)
	UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) error
}

var _ Querier = (*Queries)(nil)
