basePath: /
host: localhost:8080
info:
  contact:
    email: rohandeveloper106@gmail.com
    name: Rohan Kumar Thakur
  description: This is a Go application having JWT authentication, Unit tests,etc
    using postgresql as database
  license:
    name: GNU GENERAL PUBLIC LICENSE
  title: khushi-backend
  version: "1.0"
paths:
  /category/v1/list:
    get:
      parameters:
      - description: query params
        in: query
        name: request
        required: true
        type: string
      responses:
        "201":
          description: Created
      summary: Read all categories
schemes:
- http
swagger: "2.0"
